[package]
name = "eko"
version = "0.1.0"
edition = "2021"
description = "Transform or inspect strings"
authors = ["Craole <iamcraole@gmail.com>"]

[dependencies]
clap = { version = "4.0.3", features = ["derive", "env", "cargo", "debug"] }
convert_case = "0.6.0"
structopt = "0.3.26"
